language: generic

sudo: required

services:
  - docker

before install:
  - docker build -t wilfredmulenga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wilfredmulenga/react-test npm test

after_success:
  - docker build -t wilfredmulenga/multi-client ./client
  - docker build -t wilfredmulenga/multi-nginx ./nginx
  - docker build -t wilfredmulenga/multi-worker ./worker
  - docker build -t wilfredmulenga/multi-server ./server
# log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those images and push them to  docker hub
  - docker push wilfredmulenga/multi-client
  - docker push wilfredmulenga/multi-nginx
  - docker push wilfredmulenga/multi-worker
  - docker push wilfredmulenga/multi-server

deploy:
  provide: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-702639302567
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
